// src/layouts/AppHeader.vue
<script setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'

const props = defineProps({
  isSuperAdmin: Boolean,
  selectedStoreId: [String, Number],
  pageTitle: String,
  allowAllStores: Boolean,
  storeOptions: Array,
})

const emit = defineEmits(['toggle-collapse', 'store-change', 'logout'])
const route = useRoute()

const titleMap = {
  '/revenue': '营业额管理',
  '/schedule': '预排班',
  '/attendance': '考勤记录',
  '/daily-summary': '每日奖金汇总',
  '/personal-summary': '个人奖金明细',
  '/staff': '员工管理',
  '/accounts': '账号管理',
  '/settings': '设置',
}

const currentTitle = computed(() => props.pageTitle || titleMap[route.path] || '运营平台')
const roleLabel = computed(() => props.isSuperAdmin ? '超级管理员' : '系统管理员')
</script>

<template>
  <header class="app-header">
    <!-- SidebarTrigger -->
    <div class="app-header__trigger" @click="emit('toggle-collapse')">
      <el-icon :size="18"><Fold /></el-icon>
    </div>

    <!-- Separator -->
    <div class="app-header__separator"></div>

    <!-- Title block -->
    <div class="app-header__title-block">
      <h1 class="app-header__title">{{ currentTitle }}</h1>
      <span class="app-header__subtitle">930 PRIVATE KITCHEN · 运营管理</span>
    </div>

    <!-- Right side -->
    <div class="app-header__right">
      <!-- Search (hidden on mobile) -->
      <div class="app-header__search">
        <el-icon class="app-header__search-icon"><Search /></el-icon>
        <input
          type="text"
          class="app-header__search-input"
          placeholder="搜索员工、门店、订单..."
        />
      </div>

      <!-- Store selector -->
      <el-select
        :model-value="selectedStoreId"
        placeholder="选择门店"
        size="default"
        :disabled="!isSuperAdmin"
        class="app-header__store-select"
        @change="emit('store-change', $event)"
      >
        <el-option v-if="allowAllStores" label="全部门店" value="all" />
        <el-option
          v-for="opt in storeOptions"
          :key="opt.value"
          :label="opt.label"
          :value="opt.value"
        />
      </el-select>

      <!-- Notification bell -->
      <div class="app-header__bell">
        <el-icon :size="18"><Bell /></el-icon>
        <span class="app-header__bell-dot"></span>
      </div>

      <!-- User info pill -->
      <div class="app-header__user-pill">
        <span class="app-header__role-badge">{{ roleLabel }}</span>
        <span class="app-header__user-name">{{ pageTitle || '管理员' }}</span>
        <el-icon :size="12" class="app-header__chevron"><ArrowDown /></el-icon>
      </div>
    </div>
  </header>
</template>

<style scoped>
/* 对齐 cuisine-ops: h-16, border-b, bg-card/40, backdrop-blur-sm, sticky, z-30 */
.app-header {
  height: var(--header-height);
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 0 16px;
  background: rgba(253, 252, 249, 0.4);
  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);
  border-bottom: 1px solid var(--border);
  position: sticky;
  top: 0;
  z-index: 30;
  flex-shrink: 0;
}

/* SidebarTrigger - 对齐: text-muted-foreground hover:text-gold-bright */
.app-header__trigger {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border-radius: 6px;
  color: var(--text-muted);
  cursor: pointer;
  transition: all var(--transition-fast);
}

.app-header__trigger:hover {
  color: var(--gold-bright);
  background: var(--gold-soft);
}

/* Separator - h-6 vertical */
.app-header__separator {
  width: 1px;
  height: 24px;
  background: var(--border);
}

/* Title block */
.app-header__title-block {
  display: flex;
  flex-direction: column;
  gap: 1px;
}

.app-header__title {
  font-size: 18px;
  font-family: var(--font-display);
  color: var(--text-primary);
  line-height: 1.3;
  margin: 0;
  font-weight: 600;
}

.app-header__subtitle {
  font-size: 11px;
  color: var(--text-muted);
  letter-spacing: 0.05em;
}

/* Right side - ml-auto flex items-center gap-3 */
.app-header__right {
  margin-left: auto;
  display: flex;
  align-items: center;
  gap: 12px;
}

/* Search - hidden md:block, pl-9 w-72 */
.app-header__search {
  position: relative;
  display: none;
  width: 288px;
}

@media (min-width: 768px) {
  .app-header__search {
    display: block;
  }
}

.app-header__search-icon {
  position: absolute;
  left: 12px;
  top: 50%;
  transform: translateY(-50%);
  color: var(--text-muted);
  font-size: 16px;
  pointer-events: none;
}

.app-header__search-input {
  width: 100%;
  height: 36px;
  padding: 0 12px 0 36px;
  border: 1px solid var(--border);
  border-radius: 8px;
  background: var(--bg-secondary);
  font-size: 13px;
  color: var(--text-primary);
  outline: none;
  transition: all var(--transition-fast);
  font-family: var(--font-sans);
}

.app-header__search-input::placeholder {
  color: var(--text-muted);
}

.app-header__search-input:focus {
  border-color: var(--gold);
  box-shadow: 0 0 0 2px var(--gold-soft);
}

/* Store selector - w-56, bg-secondary/60, border-gold/20 */
.app-header__store-select {
  width: 224px;
}

.app-header__store-select :deep(.el-input__wrapper) {
  background: var(--bg-secondary);
  border: 1px solid rgba(201, 168, 76, 0.2);
  border-radius: 8px;
  box-shadow: none;
}

.app-header__store-select :deep(.el-input__wrapper:hover) {
  border-color: var(--gold);
}

.app-header__store-select :deep(.el-input__wrapper.is-focus) {
  border-color: var(--gold);
  box-shadow: 0 0 0 2px var(--gold-soft);
}

/* Notification bell - relative, text-muted-foreground, hover:text-gold-bright */
.app-header__bell {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  border-radius: 8px;
  color: var(--text-muted);
  cursor: pointer;
  transition: all var(--transition-fast);
}

.app-header__bell:hover {
  color: var(--gold-bright);
}

/* Gold dot - absolute top-2 right-2, h-1.5 w-1.5 */
.app-header__bell-dot {
  position: absolute;
  top: 6px;
  right: 6px;
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--gold);
}

/* User pill - bg-secondary/60, border, rounded-lg */
.app-header__user-pill {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 12px;
  border-radius: 10px;
  background: var(--bg-secondary);
  border: 1px solid var(--border);
}

/* Role badge - border-gold/40, text-gold-bright, bg-gold-soft */
.app-header__role-badge {
  font-size: 10px;
  font-weight: 500;
  color: var(--gold-bright);
  background: var(--gold-soft);
  border: 1px solid rgba(201, 168, 76, 0.4);
  padding: 1px 6px;
  border-radius: 4px;
  white-space: nowrap;
}

.app-header__user-name {
  font-size: 13px;
  color: var(--text-primary);
  white-space: nowrap;
}

.app-header__chevron {
  color: var(--text-muted);
}
</style>

// src/components/layout/app-header.tsx
"use client";

import { useAppStore } from "@/stores/app-store";
import { STORES } from "@/lib/stores";
import { Menu, Search, Bell } from "lucide-react";

interface AppHeaderProps {
  title?: string;
}

export function AppHeader({ title = "经营概览" }: AppHeaderProps) {
  const { selectedStoreId, setStore, toggleSidebar, user } = useAppStore();

  return (
    <header className="h-16 flex items-center gap-4 px-4 bg-card/40 backdrop-blur-sm border-b border-border sticky top-0 z-30 shrink-0">
      {/* 触发按钮 */}
      <button
        onClick={toggleSidebar}
        className="flex items-center justify-center w-8 h-8 rounded-md text-muted-foreground cursor-pointer hover:text-gold-bright hover:bg-gold-soft transition-colors"
      >
        <Menu className="w-[18px] h-[18px]" />
      </button>

      {/* 分隔线 */}
      <div className="w-px h-6 bg-border" />

      {/* 页面标题 */}
      <div className="flex flex-col gap-px">
        <h1 className="text-lg font-semibold text-foreground leading-tight m-0">
          {title}
        </h1>
      </div>

      {/* 右侧 */}
      <div className="ml-auto flex items-center gap-3">
        {/* 搜索框 */}
        <div className="relative hidden md:block w-72">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground w-4 h-4" />
          <input
            type="text"
            className="w-full h-9 pl-9 pr-3 border border-border rounded-lg bg-secondary text-sm text-foreground outline-none transition-all placeholder:text-muted-foreground focus:border-gold focus:ring-2 focus:ring-gold-soft"
            placeholder="搜索员工、门店、订单..."
          />
        </div>

        {/* 门店选择器 */}
        <select
          value={selectedStoreId}
          onChange={(e) =>
            setStore(
              e.target.value === "all" ? "all" : Number(e.target.value)
            )
          }
          className="w-56 h-9 px-3 border border-gold/20 rounded-lg bg-secondary text-sm text-foreground outline-none cursor-pointer"
        >
          <option value="all">全部门店</option>
          {STORES.map((store) => (
            <option key={store.id} value={store.id}>
              {store.name}
            </option>
          ))}
        </select>

        {/* 通知铃铛 */}
        <div className="relative flex items-center justify-center w-9 h-9 rounded-lg text-muted-foreground cursor-pointer hover:text-gold-bright transition-colors">
          <Bell className="w-[18px] h-[18px]" />
          <span className="absolute top-1.5 right-1.5 w-1.5 h-1.5 rounded-full bg-gold" />
        </div>

        {/* 用户信息 */}
        {user && (
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-secondary border border-border">
            <span className="text-[10px] font-medium text-gold-bright bg-gold-soft border border-gold/40 px-1.5 py-px rounded whitespace-nowrap">
              {user.role === "admin" ? "超级管理员" : "操作员"}
            </span>
            <span className="text-sm text-foreground whitespace-nowrap">
              {user.name || user.username}
            </span>
          </div>
        )}
      </div>
    </header>
  );
}
